#version: '1.0'
version: '2.1'

services:
  common-service:
    container_name: common-service
    build: ./
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8020:8020"
    environment:
      # 从.env 文件读取
      FLASK_ENV:
      FLASK_APP:
      SQLALCHEMY_DATABASE_URI:
      FLASK_SECRET:
      MAIL_SERVER:
      MAIL_USERNAME:
      MAIL_PASSWORD:
