version: '2.1'

services:
  mysql:
    container_name: mysql-db
    build:
      context: ./deploy/mysql
      args:
        - MYSQL_VER=5.7
    ports:
      - "3306:3306"
    volumes:
      - ./deploy/mysql/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE:
    restart: always
    networks:
      - web
    healthcheck:
      test: exit 0
    command: "--character-set-server=utf8mb4"

  redis:
    container_name: redis-db
    build:
      context: ./deploy/redis
      args:
        - REDIS_VER=5
    ports:
      - "6379:6379"
    volumes:
      - ./deploy/redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
    restart: always
    networks:
      - web
    healthcheck:
      test: exit 0

  common-service:
    container_name: common-service
    build: ./
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8020:8020"
    environment:
      # 从.env 文件读取
      FLASK_ENV:
      FLASK_APP:
      SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${$MYSQL_PASSWORD}@mysql:13306/common_web_service?charset=utf8mb4
      FLASK_SECRET:
      MAIL_SERVER:
      MAIL_USERNAME:
      MAIL_PASSWORD:
    networks:
      - web
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    links:
      - mysql:mysql
      - redis:redis
networks:
  web:
    driver: bridge

